export const ONCHANGE_EMPLOYEE = 'ONCHANGE_EMPLOYEE'

export const GET_EMPLOYEES_BEGIN = 'GET_EMPLOYEES_BEGIN'
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS'
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR'

export const LOAD_EMPLOYEES = 'LOAD_EMPLOYEES'
export const FILTER_EMPLOYEES = 'FILTER_EMPLOYEES'
export const SORT_EMPLOYEES = 'SORT_EMPLOYEES'
export const UPDATE_SORT = 'UPDATE_SORT'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const GET_CURRENT_PAGE = 'GET_CURRENT_PAGE'
export const GET_NEXT_PAGE = 'GET_NEXT_PAGE'
export const GET_PREV_PAGE = 'GET_PREV_PAGE'

export const SET_GRIDVIEW = 'SET_GRIDVIEW'
export const SET_LISTVIEW = 'SET_LISTVIEW'
